import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "@/context/LoadingContext";
import Menu from "@/components/common/Menu/menu";
import { SlugProvider } from "@/context/SlugContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LoadingProvider>
        <SlugProvider>
          <body>
            <Menu />
            {children}
          </body>
        </SlugProvider>
      </LoadingProvider>
    </html>
  );
}
